In [74]:
#write a code to interchange first and last element in the list 
def swap_first_last(lst):
    lst[0], lst[-1] = lst[-1], lst[0]  # Swapping the first and last elements
    return lst
my_list = [1, 2, 3, 4, 5]
swap_first_last(my_list)
print(my_list)  

[5, 2, 3, 4, 1]


In [75]:
#write a code to swap tow element in a list


In [76]:
#
#
#

#dictionary

In [77]:
inventory = {"ok" : 15,"hii" : 10,"miss" : 8}

In [78]:
inventory

{'ok': 15, 'hii': 10, 'miss': 8}

In [79]:
len(inventory.keys())

3

In [80]:
inventory.items()

dict_items([('ok', 15), ('hii', 10), ('miss', 8)])

operator

In [81]:
#arithmtic operator
2*3
#comparison
2==3
#logical
2<3 or 3>2

True

In [82]:
#create a conversion of celsius to farheinhirt
tem = input("enter the valu: - ")
tem = float(tem)
far = (9/5*tem)+32
print("the farhinahit tempruter is the:",far)

the farhinahit tempruter is the: 32.0


In [83]:
tem = input("enter the valu: - ")
tem = float(tem)
far = (9/5*tem)+32
if far >105:
    print("the pason infacted!!")
else:
    print("the parson is normal..")

the parson is normal..


In [84]:
tem = input("enter the valu: - ")
tem = float(tem)
far = (9/5*tem)+32
if far >80:
    print("too hot weather")
elif far>60:
    print("cold weather")
elif far<40:
    print("too cold weather")
else:
    print("good") 


too cold weather


In [85]:
#if else calculator
a =int(input ("entre the first valu :"))
b =int(input ("enter yhe secend valu"))
opp = input("enter the opperator :")

if opp=="+":
    print(a+b)
elif opp=="-":
    print(a-b)
elif opp=="*":
    print(a*b)
elif opp=="/":
    print(a/b)

conditional statment


In [86]:
frouts=['apple','banana','grapes','pichas']
print(frouts)

['apple', 'banana', 'grapes', 'pichas']


In [87]:
#looping statment - for,while

for i in frouts:
    print(i.upper())

APPLE
BANANA
GRAPES
PICHAS


In [88]:
for i in range(5):
    if i % 2==0:
        print(f"{i} even number")
    else:
        print(f"{i} odd number")

0 even number
1 odd number
2 even number
3 odd number
4 even number


In [89]:
for i in range (10):
    if i==i:
        print(i)

0
1
2
3
4
5
6
7
8
9


In [90]:
#create a mathord to find the sq all of the number and save a list
squared_list = []
for i in range(10):
    squared_list.append(i*i)
print(squared_list)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [91]:
for i in range(5):
    print(i)


0
1
2
3
4


In [92]:
for i in range(5, 0, -1):
    for j in range(i):
        print("*", end = " ")
    print(end="\n")


* * * * * 
* * * * 
* * * 
* * 
* 


In [93]:
password = input("enter the password :")
def valid_pass(password):
    upper = False
    lower = False
    digit = False
    symbol = False
    symbol_list=" / . , ; ' [ ] = - ) ( * & ^ % $ # @ ! ~ < > ? : | "
    if len(password) >8 and len(password) <20:
        for i in password:
            if i.isupper():
                upper = True
            elif i.islower():
                lower =True
            elif i.isdigit():
                digit = True
            elif i in symbol_list():
                symbol = True
if valid_pass(password):
    print("the password saved")
else:
    print("invalid password!")

invalid password!


In [94]:
import numpy as np
import random

In [95]:
arr = np.random.randint(1,5, size=(3,4))

In [96]:
arr.reshape(2,2,3)

array([[[2, 2, 1],
        [2, 2, 1]],

       [[4, 1, 3],
        [1, 3, 3]]])

In [97]:
arr.reshape(1,2,2,3)

array([[[[2, 2, 1],
         [2, 2, 1]],

        [[4, 1, 3],
         [1, 3, 3]]]])

In [98]:
arr.reshape(1,2,2,3).ndim

4

In [99]:
arr.reshape(4,3,1) #3 rows and one colum repiteat 4 times

array([[[2],
        [2],
        [1]],

       [[2],
        [2],
        [1]],

       [[4],
        [1],
        [3]],

       [[1],
        [3],
        [3]]])

In [100]:
#condition on arrY
arr1= np.random.randint(1,10, (5,6))

In [101]:
arr1

array([[5, 1, 2, 7, 5, 5],
       [1, 4, 1, 3, 9, 3],
       [9, 5, 7, 1, 8, 4],
       [2, 3, 1, 3, 1, 3],
       [6, 9, 8, 8, 8, 6]])

In [102]:
arr1.shape

(5, 6)

In [103]:
arr1.ndim

2

In [104]:
arr1.size

30

In [105]:
arr1 > 3

array([[ True, False, False,  True,  True,  True],
       [False,  True, False, False,  True, False],
       [ True,  True,  True, False,  True,  True],
       [False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True]])

In [106]:
arr1[arr1>3]

array([5, 7, 5, 5, 4, 9, 9, 5, 7, 8, 4, 6, 9, 8, 8, 8, 6])

In [107]:
arr1[arr1<3]

array([1, 2, 1, 1, 1, 2, 1, 1])

In [108]:
arr1

array([[5, 1, 2, 7, 5, 5],
       [1, 4, 1, 3, 9, 3],
       [9, 5, 7, 1, 8, 4],
       [2, 3, 1, 3, 1, 3],
       [6, 9, 8, 8, 8, 6]])

to access element in the array

In [109]:
arr1[0]

array([5, 1, 2, 7, 5, 5])

In [110]:
arr1[1]

array([1, 4, 1, 3, 9, 3])

In [111]:
arr1[1][0]

1

In [112]:
arr1

array([[5, 1, 2, 7, 5, 5],
       [1, 4, 1, 3, 9, 3],
       [9, 5, 7, 1, 8, 4],
       [2, 3, 1, 3, 1, 3],
       [6, 9, 8, 8, 8, 6]])

In [113]:
arr1[0:3]

array([[5, 1, 2, 7, 5, 5],
       [1, 4, 1, 3, 9, 3],
       [9, 5, 7, 1, 8, 4]])

In [114]:
arr1[0:3,[0,5]]

array([[5, 5],
       [1, 3],
       [9, 4]])

In [115]:
#slicing both row and colum

In [116]:
arr1

array([[5, 1, 2, 7, 5, 5],
       [1, 4, 1, 3, 9, 3],
       [9, 5, 7, 1, 8, 4],
       [2, 3, 1, 3, 1, 3],
       [6, 9, 8, 8, 8, 6]])

In [117]:
arr1[0:3, 1:3]

array([[1, 2],
       [4, 1],
       [5, 7]])

In [118]:
arr1[0:2,[0,1]]

array([[5, 1],
       [1, 4]])

In [119]:
arr1[0,[1,3]]

array([1, 7])

In [120]:
arr1

array([[5, 1, 2, 7, 5, 5],
       [1, 4, 1, 3, 9, 3],
       [9, 5, 7, 1, 8, 4],
       [2, 3, 1, 3, 1, 3],
       [6, 9, 8, 8, 8, 6]])

In [121]:
arr1[2:4,[0,3]]

array([[9, 1],
       [2, 3]])

In [122]:
arr1[2:5]

array([[9, 5, 7, 1, 8, 4],
       [2, 3, 1, 3, 1, 3],
       [6, 9, 8, 8, 8, 6]])

In [123]:
arr1[2:5]

array([[9, 5, 7, 1, 8, 4],
       [2, 3, 1, 3, 1, 3],
       [6, 9, 8, 8, 8, 6]])

In [124]:
arr1[3:5]

array([[2, 3, 1, 3, 1, 3],
       [6, 9, 8, 8, 8, 6]])

mathematical opration on 2 arry

In [125]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [126]:
arr1

array([[2, 1, 1],
       [1, 2, 1],
       [2, 1, 2]])

In [127]:
arr2

array([[2, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [128]:
arr1+arr2

array([[4, 2, 3],
       [3, 4, 2],
       [3, 3, 3]])

In [129]:
arr1*arr2

array([[4, 1, 2],
       [2, 4, 1],
       [2, 2, 2]])

In [130]:
arr1/arr2

array([[1. , 1. , 0.5],
       [0.5, 1. , 1. ],
       [2. , 0.5, 2. ]])

In [131]:
arr1-arr2

array([[ 0,  0, -1],
       [-1,  0,  0],
       [ 1, -1,  1]])

In [132]:
arr1%arr2

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [133]:
arr1, arr2

(array([[2, 1, 1],
        [1, 2, 1],
        [2, 1, 2]]),
 array([[2, 1, 2],
        [2, 2, 1],
        [1, 2, 1]]))

In [134]:
arr1<arr2

array([[False, False,  True],
       [ True, False, False],
       [False,  True, False]])

In [135]:
#matrix multipication 
#different from index wise multliplicatinon
arr1@arr2

array([[7, 6, 6],
       [7, 7, 5],
       [8, 8, 7]])

In [136]:
#dot multliplication
np.dot(arr1, arr2)


array([[7, 6, 6],
       [7, 7, 5],
       [8, 8, 7]])

In [138]:
arr4=np.zeros((3,4))

broadcasting

In [140]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [145]:
arr4 +5 

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [147]:
arr4 - 5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [150]:
a = np.array([1,2,3,4])

In [152]:
a

array([1, 2, 3, 4])

In [154]:
a.ndim

1

In [159]:
arr

array([[2, 2, 1, 2],
       [2, 1, 4, 1],
       [3, 1, 3, 3]])

In [162]:
a

array([1, 2, 3, 4])

In [163]:
arr+a

array([[3, 4, 4, 6],
       [3, 3, 7, 5],
       [4, 3, 6, 7]])

In [166]:
b= np.array([[1,2,3,4,5]])

In [168]:
#transpose
b.T 

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [170]:
arr4.T

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [172]:
arr1.T

array([[2, 1, 2],
       [1, 2, 1],
       [1, 1, 2]])

In [174]:
np.sqrt(arr)

array([[1.41421356, 1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 2.        , 1.        ],
       [1.73205081, 1.        , 1.73205081, 1.73205081]])

In [176]:
np.log10(arr)

array([[0.30103   , 0.30103   , 0.        , 0.30103   ],
       [0.30103   , 0.        , 0.60205999, 0.        ],
       [0.47712125, 0.        , 0.47712125, 0.47712125]])

In [177]:
np.exp(arr)

array([[ 7.3890561 ,  7.3890561 ,  2.71828183,  7.3890561 ],
       [ 7.3890561 ,  2.71828183, 54.59815003,  2.71828183],
       [20.08553692,  2.71828183, 20.08553692, 20.08553692]])

In [178]:
np.min(arr)

1

In [180]:
np.max(arr)

4