In [1]:
import numpy as np
import random
import pandas 
import math

numpy advance

In [3]:
arr1= np.random.randint(1,3,(3,3))
arr2= np.random.randint(1,3,(3,3))

In [4]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [1, 1, 1]])

In [5]:
#return a copy of the array collapsed into one dimension
arr1.flatten()

array([2, 2, 1, 2, 2, 1, 1, 1, 1])

In [7]:
# expened dimantion
arr = np.array([1,2,3,4])

In [8]:
arr.ndim

1

increases the dimantion by 1 at provided axis

In [9]:
np.expand_dims(arr, axis=0)

array([[1, 2, 3, 4]])

In [10]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [11]:
arr=np.zeros((3,4))

In [12]:
arr.ndim

2

In [13]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
np.expand_dims(arr, axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [15]:
np.expand_dims(arr, axis=0).ndim

3

In [16]:
a= np.array([[1], [2], [3]])

In [17]:
a

array([[1],
       [2],
       [3]])

In [18]:
a.ndim 

2

In [19]:
np.squeeze(a) #remove axis of lenght one from 'a'

array([1, 2, 3])

In [20]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [21]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [1, 1, 1]])

In [22]:
np.repeat(arr1, 2)

array([2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
np.repeat(arr1, 2, axis = 0)

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
np.repeat(arr1, 3, axis=0)

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
np.repeat(arr1, 2, axis = 1)

array([[2, 2, 2, 2, 1, 1],
       [2, 2, 2, 2, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [27]:
a

array([[1],
       [2],
       [3]])

In [28]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [29]:
np.roll(a, -1)

array([[2],
       [3],
       [1]])

In [30]:
np.roll(a, -3)

array([[1],
       [2],
       [3]])

In [33]:
c= np.array([[1,2],[3,4],[5,6]])

In [34]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
np.roll(c, -1)

array([[2, 3],
       [4, 5],
       [6, 1]])

In [38]:
np.roll(c, -2)

array([[3, 4],
       [5, 6],
       [1, 2]])

In [39]:
np.roll(c, 2)

array([[5, 6],
       [1, 2],
       [3, 4]])

In [40]:
np.roll(c,2 ,axis=0)

array([[3, 4],
       [5, 6],
       [1, 2]])

In [41]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [1, 1, 1]])

In [42]:
arr2

array([[1, 1, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [43]:
arr1+arr2

array([[3, 3, 3],
       [4, 3, 3],
       [3, 2, 3]])

In [44]:
arr1-arr2

array([[ 1,  1, -1],
       [ 0,  1, -1],
       [-1,  0, -1]])

In [45]:
arr1*arr2

array([[2, 2, 2],
       [4, 2, 2],
       [2, 1, 2]])

In [46]:
arr1 > arr2

array([[ True,  True, False],
       [False,  True, False],
       [False, False, False]])

In [47]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [1, 1, 1]])

In [48]:
~arr1

array([[-3, -3, -2],
       [-3, -3, -2],
       [-2, -2, -2]])

In [49]:
# operation on numpy string array

In [50]:
d = np.array(["pw","skills"])

In [51]:
d

array(['pw', 'skills'], dtype='<U6')

In [52]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [53]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [54]:
# mathematical function

In [55]:
arr1

array([[2, 2, 1],
       [2, 2, 1],
       [1, 1, 1]])

In [56]:
np.sin(arr1)

array([[0.90929743, 0.90929743, 0.84147098],
       [0.90929743, 0.90929743, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098]])

In [57]:
np.cos(arr1)

array([[-0.41614684, -0.41614684,  0.54030231],
       [-0.41614684, -0.41614684,  0.54030231],
       [ 0.54030231,  0.54030231,  0.54030231]])

In [58]:
np.tan(arr1)

array([[-2.18503986, -2.18503986,  1.55740772],
       [-2.18503986, -2.18503986,  1.55740772],
       [ 1.55740772,  1.55740772,  1.55740772]])

In [59]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.     ],
       [0.     , 0.     , 0.     ]])

In [60]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [62]:
np.power(arr1, 3)

array([[8, 8, 1],
       [8, 8, 1],
       [1, 1, 1]], dtype=int32)

In [63]:
np.mean(arr1)

1.4444444444444444

In [64]:
np.max(arr1)

2

In [65]:
np.min(arr1)

1

In [66]:
np.std(arr1)

0.4969039949999533

In [67]:
np.var(arr1)

0.2469135802469136

In [68]:
arr1-arr2

array([[ 1,  1, -1],
       [ 0,  1, -1],
       [-1,  0, -1]])

In [69]:
np.subtract(arr1, arr2)

array([[ 1,  1, -1],
       [ 0,  1, -1],
       [-1,  0, -1]])

In [70]:
arr1*arr2

array([[2, 2, 2],
       [4, 2, 2],
       [2, 1, 2]])

In [71]:
np.multiply(arr1, arr2)

array([[2, 2, 2],
       [4, 2, 2],
       [2, 1, 2]])

In [73]:
np.mod(arr1, arr2) # return element wise remainder

array([[0, 0, 1],
       [0, 0, 1],
       [1, 0, 1]])

In [75]:
np.power(arr1, 4)

array([[16, 16,  1],
       [16, 16,  1],
       [ 1,  1,  1]], dtype=int32)

In [76]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ]])

In [77]:
# sort search 

In [79]:
e =np.array([5,6,1,2])

In [80]:
e

array([5, 6, 1, 2])

In [81]:
np.sort(e)

array([1, 2, 5, 6])

In [82]:
f = np.array([123, 244, 2334, 457, 8886, 2435])

In [83]:
f

array([ 123,  244, 2334,  457, 8886, 2435])

In [84]:
np.sort(f)

array([ 123,  244,  457, 2334, 2435, 8886])

find indices where element should be inserted be inserted to main order.

In [87]:
np.searchsorted(f, 447)

2

In [90]:
f = np.array([123, 0, 244, 2334, 0, 457, 0, 8886, 0, 2435])

In [91]:
f

array([ 123,    0,  244, 2334,    0,  457,    0, 8886,    0, 2435])

In [92]:
np.count_nonzero(f)

6

In [94]:
f[f > 0]

array([ 123,  244, 2334,  457, 8886, 2435])

In [95]:
np.where(f>0)

(array([0, 2, 3, 5, 7, 9], dtype=int64),)

In [96]:
np.extract(f>0, f)

array([ 123,  244, 2334,  457, 8886, 2435])

In [99]:
#bytes swap

In [98]:
f

array([ 123,    0,  244, 2334,    0,  457,    0, 8886,    0, 2435])

In [101]:
f.byteswap()

array([ 2063597568,           0,  -201326592,   503906304,           0,
        -922681344,           0, -1239285760,           0, -2096562176])

In [102]:
#matrix 2d array

In [105]:
import numpy.matlib as nm

In [106]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [109]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [110]:
# numpy linear algebra

In [115]:
arr1 = np.random.randint(1, 10, (4,4))
arr2 = np.random.randint(1, 10, (4,4))

In [116]:
arr1

array([[3, 2, 7, 5],
       [7, 8, 5, 3],
       [9, 8, 5, 3],
       [1, 5, 2, 9]])

In [117]:
arr2

array([[5, 7, 4, 5],
       [8, 9, 1, 1],
       [8, 7, 4, 4],
       [8, 7, 1, 6]])

In [119]:
arr1 @ arr2

array([[127, 123,  47,  75],
       [163, 177,  59,  81],
       [173, 191,  67,  91],
       [133, 129,  26,  72]])

In [120]:
arr1

array([[3, 2, 7, 5],
       [7, 8, 5, 3],
       [9, 8, 5, 3],
       [1, 5, 2, 9]])

In [121]:
np.linalg.det(arr1)

-732.0000000000005

In [122]:
np.linalg.det(arr2)

-482.9999999999998

In [123]:
np.linalg.inv(arr1)

array([[ 2.46716228e-17, -5.00000000e-01,  5.00000000e-01,
         7.70988212e-18],
       [-1.06557377e-01,  4.97267760e-01, -3.52459016e-01,
         1.09289617e-02],
       [ 1.55737705e-01,  2.73224044e-01, -2.54098361e-01,
        -9.28961749e-02],
       [ 2.45901639e-02, -2.81420765e-01,  1.96721311e-01,
         1.25683060e-01]])

In [124]:
np.linalg.inv(arr2)

array([[-0.30020704, -0.04347826,  0.29606625,  0.06004141],
       [ 0.2484472 ,  0.17391304, -0.27950311, -0.04968944],
       [ 0.06625259, -0.08695652,  0.25879917, -0.21325052],
       [ 0.09937888, -0.13043478, -0.11180124,  0.18012422]])

In [125]:
a = np.array([[2, 3.4, 5],[3, -5, 8],[7, 8, -1]])

In [126]:
a

array([[ 2. ,  3.4,  5. ],
       [ 3. , -5. ,  8. ],
       [ 7. ,  8. , -1. ]])

In [128]:
b = np.array([14, 17, 0])

In [129]:
b

array([14, 17,  0])

In [130]:
np.linalg.solve(a,b)

array([-0.23358051,  0.5217161 ,  2.53866525])

In [1]:
#E bill

In [2]:
def e_bill(n):
    if n<=500:
        print("bill rupi is : ", n*5 )
    elif n>500 and n<=700:
        print("bill rupi is : ", n*10)
    elif n>700 and n<=1000:
        print("bill rupi is : ", n*15)
    elif n>1000:
        print("bill rupi is : ", n*20)


In [36]:
for i in range(3):
    a = input("enter the coustomar name :")
    print("enter the coustomar name is :", a)
    n = int(input("enter the unit coustomar have use :"))
    e_bill(n)

enter the coustomar name is : sujay
bill rupi is :  13500
enter the coustomar name is : payel
bill rupi is :  12000
enter the coustomar name is : raj
bill rupi is :  6000
